version: "3.9"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    platform: linux/x86_64
    image: mysql:5.7.44
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379